bluenviron/gortsplib

conn-client-udpl.go
conn-client.go

From our discussion in #2. I thought this would be the best way to resolved it.

Added handlers for custom dialer and custom udp listener

---

pkg/headers/keyval.go

This can be useful for debugging.

keyval: log which key could not be found

---

README.md
client.go
client_read_test.go
clientconn.go
examples/client-read-partial/main.go
examples/client-read-pause/main.go
pkg/headers/range.go
pkg/headers/range_test.go

client: implement Seeking

---

README.md
examples/server-tls/main.go
examples/server/main.go
go.mod
go.sum
pkg/headers/transport.go
pkg/headers/transport_test.go
server.go
server_publish_test.go
server_read_test.go
server_test.go
serverconn.go
serverhandler.go
serversession.go
serverstream.go
serverudpl.go

server: implement reading with multicast

---

track.go
track_test.go

Fix SDP parsing of H264 tracks of some cameras

---

pkg/sdp/sdp.go
pkg/sdp/sdp_test.go

Fixes #82 
I decided on a different approach than those mentioned in the issue.  Seems cleaner and doesn't mess with the flow of the existing code.  Test case is passing.

Add support for some FLIRs SDP timing format.

---

client.go
client_read_test.go

client keepalive reset by session timeout

reset client keepalive by session timeout

---

client.go
client_read_test.go
pkg/headers/transport.go
pkg/headers/transport_test.go

clientudp: parse source header

---

README.md
examples/client-publish-codec-vp9/main.go
examples/client-read-codec-opus/main.go
examples/client-read-codec-vp9/main.go
pkg/rtpvp8/rtpvp8.go
pkg/rtpvp9/decoder.go
pkg/rtpvp9/decoder_test.go
pkg/rtpvp9/encoder.go
pkg/rtpvp9/encoder_test.go
pkg/rtpvp9/rtpvp9.go

add RTP/VP9 encoder and decoder

---

README.md
examples/client-publish-codec-h265/main.go
examples/client-read-codec-h265/main.go
pkg/rtph264/decoder_test.go
pkg/rtph265/decoder.go
pkg/rtph265/decoder_test.go
pkg/rtph265/encoder.go
pkg/rtph265/encoder_test.go
pkg/rtph265/rtph265.go
track_h265.go
track_test.go

add H265 decoder and encoder

---

pkg/media/media.go
pkg/media/medias_test.go
serverconn.go

media: preserve recvonly, sendonly and sendrecv attributes

---

pkg/format/format.go
pkg/format/format_test.go

https://github.com/aler9/rtsp-simple-server/issues/1267

format: fix compatibility with some TP-Link cameras

---

README.md
pkg/formats/format.go
pkg/formats/format_test.go
pkg/formats/g711.go
pkg/formats/g722.go
pkg/formats/generic.go
pkg/formats/h264.go
pkg/formats/h265.go
pkg/formats/lpcm.go
pkg/formats/mjpeg.go
pkg/formats/mpeg2_audio.go
pkg/formats/mpeg2_video.go
pkg/formats/mpeg4_audio.go
pkg/formats/mpeg4_video.go
pkg/formats/mpeg4_video_test.go
pkg/formats/opus.go
pkg/formats/vorbis.go
pkg/formats/vp8.go
pkg/formats/vp9.go

related to https://github.com/aler9/mediamtx/issues/1550

add MPEG-4 video format

---

client.go
client_media.go
client_play_test.go
client_udpl.go
restrict_network.go
server.go
server_udpl.go

(https://github.com/aler9/mediamtx/issues/1665)

do not listen on IPv6 when host is 0.0.0.0

---

README.md
client.go

(https://github.com/aler9/mediamtx/issues/1403)

fix timeout with some cameras by decreasing interval between keepalives

---

client.go
pkg/rtptime/decoder.go
pkg/rtptime/encoder.go
pkg/rtptime/encoder_test.go

rtptime: fix time encoding on arm32 (#274)

---

client.go

this fixes a regression introduced with #277

client: fix sending keepalives (https://github.com/bluenviron/mediamtx/issues/1812)

---

client_udp_listener.go
server_udp_listener.go

(https://github.com/bluenviron/mediamtx/discussions/1744)

fix using multicast when a single interface doesn't support it

---

pkg/sdp/sdp.go
pkg/sdp/sdp_test.go

Fixes https://github.com/bluenviron/mediamtx/issues/2128

fix SDP unmarshaling with Vurix NVR (https://github.com/bluenviron/mediamtx/issues/2128)

---

client.go
client_format.go
client_media.go
client_play_test.go
client_record_test.go
client_udp_listener.go
pkg/rtcpreceiver/rtcpreceiver.go
pkg/rtcpreceiver/rtcpreceiver_test.go
pkg/rtcpsender/rtcpsender.go
pkg/rtcpsender/rtcpsender_test.go
server.go
server_play_test.go
server_record_test.go
server_session.go
server_session_format.go
server_session_media.go
server_stream.go
server_stream_media.go
server_udp_listener.go

add Client.PacketNTP(), ServerSession.PacketNTP()

---

client.go
client_play_test.go
pkg/description/media_test.go
pkg/description/session.go
pkg/description/session_test.go
pkg/sdp/sdp.go
server_conn.go

Fixes https://github.com/bluenviron/mediamtx/issues/979

allow publishers to set the title of the stream

---

README.md
examples/client-read-format-h264-convert-to-jpeg/main.go
examples/client-read-format-h264-save-to-disk/main.go
examples/client-read-format-h264/h264_decoder.go
examples/client-read-format-h265-convert-to-jpeg/h265_decoder.go
examples/client-read-format-h265-convert-to-jpeg/main.go
examples/client-read-format-h265-save-to-disk/main.go
examples/client-read-format-h265-save-to-disk/mpegts_muxer.go
examples/client-read-format-h265/h265_decoder.go
examples/client-read-format-h265/main.go
examples/server-h264-save-to-disk/mpegts_muxer.go
go.mod
go.sum

improve H264/H265 examples (#355) (#375)

---

client_reader.go

this happened when a interleaved frame was read during shutdown.

client: fix race condition that can lead to crash

---

client.go
client_play_test.go
pkg/liberrors/client.go
pkg/liberrors/server.go

Fixes https://github.com/bluenviron/mediamtx/issues/2302

client: support cameras that don't reply to keepalives

---

.golangci.yml
client.go
client_media.go
client_udp_listener.go
constants.go
pkg/multicast/multi_conn.go
pkg/multicast/multicast.go
pkg/multicast/read_from_lin.go
pkg/multicast/read_from_win.go
pkg/multicast/single_conn.go
server_udp_listener.go

Fixes https://github.com/bluenviron/mediamtx/issues/2029

fix reading and writing multicast packets in case of multiple interfaces

---

README.md
pkg/multicast/multi_conn_lin.go
pkg/multicast/single_conn_lin.go

(https://github.com/bluenviron/mediamtx/issues/2133)

remove useless SO_REUSEPORT

---

pkg/sdp/sdp.go
pkg/sdp/sdp_test.go

Fixes https://github.com/bluenviron/mediamtx/issues/2473

support SDPs without session name

---

server_play_test.go
server_stream.go
server_stream_format.go

add BytesSent to ServerStream (to allow MediaMTX to gather bytes sent on all paths)

add BytesSent to ServerStream (to allow MediaMTX to gather bytes sent on all paths)

---

README.md
client.go
client_format.go
client_media.go
client_play_test.go
examples/client-play-backchannel/main.go
pkg/description/media.go
pkg/description/session_test.go
server_conn.go

 client: support writing to ONVIF back channels (#101) 

---

pkg/sdp/sdp.go
pkg/sdp/sdp_test.go

sdp: fix parsing SDP from UDP technology cameras (#474)

---

README.md
examples/client-play-format-av1/main.go
examples/client-play-format-g711/main.go
examples/client-play-format-g722/main.go
examples/client-play-format-h264-convert-to-jpeg/main.go
examples/client-play-format-h264-save-to-disk/main.go
examples/client-play-format-h264/main.go
examples/client-play-format-h265-convert-to-jpeg/main.go
examples/client-play-format-h265-save-to-disk/main.go
examples/client-play-format-lpcm/main.go
examples/client-play-format-mjpeg/main.go
examples/client-play-format-mpeg4audio-save-to-disk/main.go
examples/client-play-format-mpeg4audio/main.go
examples/client-play-format-opus-save-to-disk/main.go
examples/client-play-format-opus-save-to-disk/mpegts_muxer.go
examples/client-play-format-opus/main.go
examples/client-play-format-vp8/main.go
examples/client-play-format-vp9/main.go
examples/client-record-format-mpeg4audio/main.go
pkg/format/rtpmpeg4audio/encoder.go

add client-play-format-opus-save-to-disk (#487)

---

pkg/description/media.go
pkg/description/session_test.go

fix compatibility with some TP-Link cameras (#509)

---

pkg/sdp/sdp.go
pkg/sdp/sdp_test.go

Fixes https://github.com/bluenviron/mediamtx/issues/2708

fix SDP error with AXIS 221 (https://github.com/bluenviron/mediamtx/issues/2708)

---

pkg/format/mpeg4_audio.go

https://github.com/bluenviron/mediamtx/issues/3590

fix panic in MPEG4Audio.GetConfig()

---

pkg/headers/transport.go
pkg/liberrors/server.go
server_record_test.go
server_session.go

Fixes https://github.com/bluenviron/mediamtx/issues/3677

server: fix panic when recording with wrong transport header

---

pkg/sdp/sdp.go
pkg/sdp/sdp_test.go

Fixes bluenviron/mediamtx#3583

fix reading from Wisenet NVR (bluenviron/mediamtx#3583)

---

pkg/liberrors/server.go
server_play_test.go
server_session.go

Fixes bluenviron/mediamtx#4025

server: fix crash with invalid SETUP request (bluenviron/mediamtx#4025)

---

pkg/sdp/sdp.go
pkg/sdp/sdp_test.go

fix SDP compatibility with some Uniview cameras (#618)

---

client.go
client_play_test.go

Fixes #575
Keepalives are now sent when writing to back channels too.

client: fix timeout when writing to back channels (#575)

---

client.go
server_session.go
server_stream.go

Build aggregated statistics by using already-available data.

improve Stats performance

---

examples/client-play-to-record/main.go

fix crash in client-play-to-record example (#841)

---

client.go
client_media.go
client_play_test.go
client_udp_listener.go
server_conn.go
server_play_test.go
server_record_test.go
server_session.go
server_session_media.go
server_stream.go

Client: Stats
ServerConn: Session, Stats
ServerSession: State, Stats, Medias, Path, Query, Stream, SetuppedSecure, SetuppedTransport, AnnouncedDescription

make most methods thread safe

---

pkg/sdp/sdp.go
pkg/sdp/sdp_test.go

Fixes bluenviron/mediamtx#5008

sdp: fix compatibility with a Uniview camera (bluenviron/mediamtx#5008)
