bluenviron/gortsplib

- track.go
- track_test.go
I'm using `vlc` as a RTSP server:
```bash
vlc -I dummy --verbose=2 --loop $sample_file \
--network-caching=1500 \
--sout-all --sout-keep \
--sout='#gather:rtp{sdp=rtsp://:8554/sample.mkv}'
```
which generates the `fmtp` attribute as follows:
`
fmtp:96 packetization-mode=1;profile-level-id=64001f;sprop-parameter-sets=Z2QAH6zZQFAFuwFsgAAAAwCAAAAeB4wYyw==,aOvjyyLA;
`
By splitting the string with `;`, there will be an empty `kv` at the end of the substrings, which should be skipped.
> track: fix parsing fmtp attribute from a VLC generated SDP

- pkg/headers/keyval.go
- pkg/headers/keyval_test.go
- pkg/headers/rtpinfo_test.go
- pkg/headers/session_test.go
- pkg/headers/transport.go
- pkg/headers/transport_test.go
Resolves issue #34 by ...
1. Allowing transport header field keys without values (ex: `key1;key2=value;key3`).
2. Parsing all header fields (specifically stream protocol and stream delivery options) without expecting them in a specific order.
New tests for value-less-keys have also been added and old error-tests checking for errors on value-less-keys have been removed.
> Decode unconventionally sorted transport header

- client_test.go
- clientconn.go
Altough not explicitly allowed by RFC2326, some servers respond with
a `Content-Type` header field that contains charset information as
described in RFC2616 (sec 14.17).
The parser currently fails to read from such connections and bails
with
`unsupported Content-Type header '[application/sdp; charset=utf-8]'`
Change this by ignoring everything after a semicolon.
> Add support for charset information in content-type header

- serverconn.go
When a server handler implements `OnDescribe()` it may return a
`base.Reponse` that carries a body, along with a `nil` stream.
`handleRequest()` should support that, and not override `res.Body`, and,
more importantly, not dereference the returned `nil` pointer.
> serverconn: allow passing of raw base.Response.Body from Describe callbacks

- pkg/sdp/sdp.go
- pkg/sdp/sdp_test.go
I found that my rtsp source had hexadecimal session ID when using rtsp-simple-server.
The error is shown as following:
**ERR: sdp: invalid numeric value `0xfbc380` (o=- 0xfbc380 1 IN IP4 192.168.2.9)**
I added this code to your work and it worked just fine.  I hope this could be merged into your work. Thanks!
> handle hex session id

- track_h264.go
The `sprop-parameter-sets` parameter in a SDP description of a H.264 stream could contain more that two fields. These fields could be considered extradata. Some tools like ffmpeg incorporate them if they are available. You can read about specs of this parameter at https://www.ietf.org/archive/id/draft-lennox-avt-h264-source-fmtp-00.html#anchor3 .
This is an example of a working description:
`a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z01AKJJSgPAIj7wEQAAAAwBAAAAMo8WLZYA=,aP48gAA=; profile-level-id=4D4028`
And this is another example that fails without this PR:
`a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAKawTMUB4BEfeA+oCAgPgAAADACAAAAZSgA==,aPqPLA==,aF6jzAMA; profile-level-id=640029`
So assuming the optional presence of more than two fields in the …
> fix ExtractConfigH264() when extradata is present

- server_publish_test.go
- track.go
- track_aac.go
- track_aac_test.go
- track_generic.go
- track_h264.go
- track_h264_test.go
- track_opus.go
- track_opus_test.go
- tracks.go
Prior to commit 6d5bf0c1bb90f8e6b3c80acc32ac37f958075303, gortsplib clients could access the media description through the `Media` field, which could be used to access SDP fields and media type (audio vs. video). When this was replaced with the private `mediaDescription`, that ability was lost. This PR exposes `MediaDescription()` to restore access to these fields.
> track: expose MediaDescription() and Set/GetControl()

- pkg/sdp/sdp.go
- pkg/sdp/sdp_test.go
There are some rtsp streams, the session id in sdp is hex, such as
`103bdb6f`
`0X103bdb6f`
There will be an `sdp: invalid numeric value ``103bdb6f`` (o=- 103bdb6f 1 IN IP4 10.1.72.244)` error
> Get hex session id from sdp

- pkg/sdp/sdp.go
- pkg/sdp/sdp_test.go
We use the IOI trk-101. This device returns an origin-field with a
trailing space. This triggered the special case for some onvif2 cameras.
This resulted in a double unicast-address, causing a shift in the
fields. Eventually resulting in an exception when nettype was
interpret as sess-version.
This commit fixes this issue and adds a testcase that includes a
trailing whitespace.
> Fix handling of trailing space in origin-field

- client.go
It's helpful for debugging to be able to override the hardcoded `gortsplib` User-Agent header, as we can have multiple gortsplib-based clients. I'd also be open to making this a config option or a parameter to the Client, but this was the lowest impact change. 
It also has the advantage that this parameter can be changed by e.g., docker image without rebuilding.
> client: allow UserAgent to be set

- client.go
- client_read_test.go
Consider a source RTSP server that requires a set of username/password credentials. The source server is also load balancing between its' other nodes. Source server responds with a _redirected_ URL, however, due to the nature of web redirection, the credentials used to access the source server is not included in the redirection URL. When `gortsplib` is handling the redirection, it does not factor in any credentials.
The proposed changes in this PR adds the flag `PersistCredentialsOnRedirect` to the `Client`, setting it to true results in the originally used credentials (username/password) being carried over onto the redirected URL (when the source server responds with the redirection response). This is ideal for source servers that are consistently redirecting to one of its' other servers …
> Persist credentials on source redirections

- track_h264.go
This avoids adding fmtp lines of the form "sprop-parameter-sets=" with no value (which leads to malformed SDPs).
> track_h264: avoid appending empty sps to fmtp line

- pkg/headers/transport.go
- pkg/headers/transport_test.go
- server_test.go
- serversession.go
Error 400 was being returned when Transport header contained multiple transports:
invalid transport header: invalid ports (45228-45229, RTP/AVP/TCP)
Header sent by client in request:
Transport: RTP/AVP;unicast;client_port=45228-45229, RTP/AVP/TCP;unicast;interleaved=0-1
Per RFC2326 section 12.39, the Transport header can contain multiple transports separated by comma.
> Fix parsing of Transport header with multiple transports.

- pkg/rtph264/decoder.go
- pkg/rtph264/decoder_test.go
- pkg/rtph264/encoder.go
- pkg/rtph264/encoder_test.go
- pkg/rtph264/rtph264.go
Intact NALUs received after corrupted NALUs were wrongly discarded.
> rtph264: fix decode error

- pkg/mpeg4audio/config.go
- pkg/mpeg4audio/config_test.go
- pkg/mpeg4audio/objecttype.go
Fixed play he_aac_v1 warning via ffmpeg
```
[aac @ 0x11f73bd90] Audio object type SBR+0 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
```
Fixed publish he_aac_v2 error via ffmpeg
```
Could not write header for output file #0 (incorrect codec parameters ?): Server returned 400 Bad Request
Error initializing output stream 0:1 -- 
```
> Improved support for he_aac

- client.go
- client_play_test.go
- pkg/liberrors/client.go
(https://github.com/aler9/rtsp-simple-server/issues/1105)
when a camera receives a UDP request and replies with a TCP response, switch protocol from UDP to TCP.
> client: improve automatic protocol switching

- pkg/formatdecenc/rtph264/decoder.go
- pkg/formatdecenc/rtph264/decoder_test.go
> formatdecenc/rtph264: fix removing Annex-B when first packet is not Annex-B (#199) (#200)

- examples/client-publish-format-opus/main.go
- pkg/format/format_test.go
- pkg/format/opus.go
- pkg/format/opus_test.go
- pkg/media/medias_test.go
RFC7587 mandates 48khz as sample rate and 2 channels inside the SDP. These values can be dynamically adjusted by the stream, but they must not be touched inside the SDP.
> make Opus SDP always return 48khz and 2 channels

- pkg/formatdecenc/rtph264/decoder.go
- pkg/formatdecenc/rtph264/encoder.go
- pkg/formatdecenc/rtph265/decoder.go
- pkg/formatdecenc/rtph265/encoder.go
- pkg/formatdecenc/rtplpcm/decoder.go
- pkg/formatdecenc/rtplpcm/encoder.go
- pkg/formatdecenc/rtpmjpeg/decoder.go
- pkg/formatdecenc/rtpmjpeg/encoder.go
- pkg/formatdecenc/rtpmpeg4audio/decoder.go
- pkg/formatdecenc/rtpmpeg4audio/encoder.go
- pkg/formatdecenc/rtpsimpleaudio/decoder.go
- pkg/formatdecenc/rtpsimpleaudio/encoder.go
- pkg/formatdecenc/rtpvp8/decoder.go
- pkg/formatdecenc/rtpvp8/encoder.go
- pkg/formatdecenc/rtpvp9/decoder.go
- pkg/formatdecenc/rtpvp9/encoder.go
- pkg/rtptime/decoder.go
- pkg/rtptime/decoder_test.go
- pkg/rtptime/encoder.go
- pkg/rtptime/encoder_test.go
previous formula was: uint32(a + uint32(b))
this formula overflows two times, while it should overflow once. new formula is: uint32(uint64(a) + uint64(b))
> fix timestamp encode error after some hours

- client_play_test.go
- client_record_test.go
- client_test.go
- pkg/media/media.go
- pkg/media/medias_test.go
- server_conn.go
- server_play_test.go
- server_record_test.go
- server_test.go
this is necessary in order to make GStreamer's rtspsrc process query parameters correctly.
> server: use absolute RTSP URL as control attribute

- pkg/codecs/jpeg/jpeg.go
- pkg/formatdecenc/rtpmjpeg/encoder.go
Added support for handling comment markers (0xF0) by skipping their data.
> Support JPEG comment markers in MJPEG encoder

- client.go
- client_play_test.go
- client_test.go
- pkg/media/medias.go
- server_conn.go
- server_play_test.go
- server_record_test.go
- server_session.go
- server_stream.go
- server_stream_media.go
This is needed to support clients like the Grandstream GXV3500.
Fixes https://github.com/bluenviron/gortsplib/issues/190
> use normalized trackID in place of mediaUUID

- pkg/sdp/sdp.go
- pkg/sdp/sdp_test.go
- pkg/sdp/testdata/fuzz/FuzzUnmarshal/336ade141e5e643f
- pkg/sdp/testdata/fuzz/FuzzUnmarshal/3f21eeb108705afd
- pkg/sdp/testdata/fuzz/FuzzUnmarshal/59e226a0079e1776
> fix SDP unmarshaling with some Chinese cameras (#201)

- pkg/liberrors/server.go
- server_play_test.go
- server_session.go
(https://github.com/aler9/mediamtx/issues/1650)
> server: support TCP read requests without interleaved IDs

- pkg/formats/format_test.go
- pkg/formats/mpeg4_audio_latm.go
https://github.com/aler9/mediamtx/issues/1716
> fix parsing of MP4A-LATM formats with no channels and object

- client_media.go
- client_play_test.go
- client_record_test.go
- server_record_test.go
- server_session_media.go
when reading with TCP and packet has an unknown format.
> client: return an error in case of invalid packet

- client.go
- client_test.go
- pkg/url/url.go
> client: support URLs with IPv6 and no port (#313)

- pkg/rtcpreceiver/rtcpreceiver.go
Fixes https://github.com/bluenviron/mediamtx/issues/1739
> generate RTCP receiver reports even before receiving RTCP sender reports

- pkg/formats/av1.go
- pkg/formats/format.go
- pkg/formats/format_test.go
- pkg/formats/g711.go
- pkg/formats/g722.go
- pkg/formats/g726.go
- pkg/formats/generic.go
- pkg/formats/h264.go
- pkg/formats/h265.go
- pkg/formats/lpcm.go
- pkg/formats/mjpeg.go
- pkg/formats/mpeg1_audio.go
- pkg/formats/mpeg1_video.go
- pkg/formats/mpeg4_audio_generic.go
- pkg/formats/mpeg4_audio_latm.go
- pkg/formats/mpeg4_video_es.go
- pkg/formats/mpegts.go
- pkg/formats/opus.go
- pkg/formats/speex.go
- pkg/formats/vorbis.go
- pkg/formats/vp8.go
- pkg/formats/vp9.go
> discard invalid video tracks (#381)

- pkg/format/format_test.go
- pkg/format/h264.go
- pkg/format/h265.go
> fix compatibility with Annex-B encoded H264 SPS/PPS (#402)

- pkg/format/format_test.go
- pkg/format/h264.go
Fixes https://github.com/bluenviron/mediamtx/issues/2348
> discard invalid H264 parameters

- client.go
- client_test.go
> client: support receiving responses with spaces in CSeq (#437)

- pkg/sdp/sdp.go
- pkg/sdp/sdp_test.go
Fixes https://github.com/bluenviron/mediamtx/issues/2558
> sdp: support cameras with decimal numbers in origin

- server_conn.go
- server_test.go
This fixes the following panic when handling certain invalid requests:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x5601e7562614]
goroutine 206 [running]:
github.com/bluenviron/gortsplib/v4/pkg/url.(*URL).RTSPPathAndQuery(...)
github.com/bluenviron/gortsplib/v4@v4.3.0/pkg/url/url.go:81
github.com/bluenviron/gortsplib/v4.(*ServerConn).handleRequestInner(0xc0001a8200, 0xc00064c7c0)
github.com/bluenviron/gortsplib/v4@v4.3.0/server_conn.go:221 +0x174
github.com/bluenviron/gortsplib/v4.(*ServerConn).handleRequestOuter(0xc0001a8200, 0xc00064c7c0)
github.com/bluenviron/gortsplib/v4@v4.3.0/server_conn.go:382 +0x67
github.com/bluenviron/gortsplib/v4.(*ServerConn).runInner(0xc0001a8200) …
```
> fix nil url deref when handling invalid requests

- README.md
- pkg/sdp/sdp.go
- pkg/sdp/sdp_test.go
This will skip the C: attribute when containing SM. This is added by Avigilon cameras, and make the current SDP formatter fail. Original issue: https://github.com/bluenviron/gortsplib/issues/479
> Fixing issue for SDP avigilon when activating onvif backchannel #479

- README.md
- examples/client-record-format-g711/main.go
- examples/client-record-format-g722/main.go
- examples/client-record-format-h264/main.go
- examples/client-record-format-h265/main.go
- examples/client-record-format-lpcm/main.go
- examples/client-record-format-mjpeg-from-image/main.go
- examples/client-record-format-mjpeg/main.go
- examples/client-record-format-mpeg4audio/main.go
- examples/client-record-format-opus/main.go
- examples/client-record-format-vp8/main.go
- examples/client-record-format-vp9/main.go
- examples/client-record-options/main.go
- examples/client-record-pause/main.go
> add example client-record-format-mjpeg-from-image (#489)

- server_play_test.go
- server_session.go
A recent behavioral change introduced by [PR #2244](https://github.com/bluenviron/mediamtx/pull/2244) has inadvertently caused a bug affecting the initialization timing of the RTSP server, which now waits until the first playback connection attempt. This change has resulted in playback failures in some video players due to the timing of the server's start-up sequence. The root of the issue lies in the `OnSetup` handler in [server_session.go](https://github.com/bluenviron/gortsplib/blob/877771e4c547546db3c93cec4381636648cf9efc/server_session.go#L747), which activates the RTSP server processor found in [stream.go](https://github.com/bluenviron/mediamtx/blob/3e7cc0470f69b90c0d6dec3340514b1fd7d99701/internal/stream/stream.go#L102).
The server's setup process allows `gortsplib` to …
> avoid returning partial RTP-Info header, omit seq/rtptime if needed

- pkg/format/rtpmjpeg/encoder.go
- pkg/format/rtpmjpeg/header_jpeg.go
Type 0 corresponds to YUV 4:2:2. Since this header is passed directly to the JPEG header, no additional changes are necessary for support. See the type field here: https://datatracker.ietf.org/doc/html/rfc2435#section-4.1
I have a stream producing YUV 4:2:2 mjpeg over RTSP and have confirmed manually that piping this through ffmpeg as a jpeg decoder results in correct decoding.
> Fix mjpeg type 0 check

- client.go
- client_play_test.go
- client_record_test.go
> client: omit mode from Transport header (#611) (#574)

- pkg/format/h264_test.go
- pkg/format/h265.go
- pkg/format/h265_test.go
- pkg/format/testdata/fuzz/FuzzH264PTSEqualsDTS/048b606517c23baf
- pkg/format/testdata/fuzz/FuzzH264PTSEqualsDTS/0d7efebfbe993205
- pkg/format/testdata/fuzz/FuzzH264PTSEqualsDTS/55cc57e8de6f7821
- pkg/format/testdata/fuzz/FuzzH264PTSEqualsDTS/6347df174e34a4bd
- pkg/format/testdata/fuzz/FuzzH264PTSEqualsDTS/83e07aca85794b54
- pkg/format/testdata/fuzz/FuzzH264PTSEqualsDTS/a831486d4a428ccd
- pkg/format/testdata/fuzz/FuzzH264PTSEqualsDTS/ba42460e5506f2bc
- pkg/format/testdata/fuzz/FuzzH264PTSEqualsDTS/caf81e9797b19c76
- pkg/format/testdata/fuzz/FuzzH265PTSEqualsDTS/19981bffc2abbaf1
- pkg/format/testdata/fuzz/FuzzH265PTSEqualsDTS/463b273d21ba371a
- pkg/format/testdata/fuzz/FuzzH265PTSEqualsDTS/6e0463cbdc2d559f
- pkg/format/testdata/fuzz/FuzzH265PTSEqualsDTS/7c106d2d11e725ec
- pkg/format/testdata/fuzz/FuzzH265PTSEqualsDTS/a564d03307332bc8
- pkg/format/testdata/fuzz/FuzzH265PTSEqualsDTS/b2089cb22b868c96
- pkg/format/testdata/fuzz/FuzzH265PTSEqualsDTS/b88d0a1c039b8eca
- pkg/format/testdata/fuzz/FuzzH265PTSEqualsDTS/c4389a565e828050
- pkg/format/testdata/fuzz/FuzzH265PTSEqualsDTS/e8bff8fcc87530c8
- pkg/format/testdata/fuzz/FuzzH265PTSEqualsDTS/eb4593a9592045ab
Fixes bluenviron/mediamtx#3754
> fix panic when checking pts = dts on H265 (bluenviron/mediamtx#3754)

- pkg/description/media.go
- pkg/description/media_test.go
If the control value is the full path beginning with a `/` and the base does not end in a slash an extra slash will be added.
related to this [issue](https://github.com/bluenviron/mediamtx/issues/3517) on mediamtx
> fix generating media URL with leading slash in control attribute (bluenviron/mediamtx#3517)

- pkg/format/format.go
- pkg/format/format_test.go
Media type payload unassigned number 35 is being evaluated as media type payload dynamic range (96-127).  Added some tests to verify these new changes on format_test
Currently, the video surveillance cameras of the bosch security branch offer rtsp with some peculiarities over the standard.
Instead of using the convenience media payload, which is usually 96, they use 35. This means that the camera format is not detected correctly.
This happens at least for the model FLEXIDOME IP starlight 8000i - 7.62.0003 (03500762)
There is an initial note on the first page of the document (manual) on how to use RTSP protocol in Bosch VIP cameras where it is specified that they use payload type 35 (https://community.boschsecurity.com/varuj77995/attachments/varuj77995/bt_community-tkb-video/241/1/RTSP%20us …
> 630 - Add media type payload unassigned number 35 in format

- server_play_test.go
- server_session.go
Return error 'can't setup medias with different protocols' when trying to use UDP and TCP in sequence.
> server: fix error message

- pkg/format/rtph264/decoder.go
- pkg/format/rtph264/decoder_test.go
Some IP cameras (e.g. CostarHD) have been observed to emit single fragment RTP FU-A packets, with start and end bit both set, for sufficiently small H.264 P-frames. Rather than emit an error, workaround such non-compliant frames.
> rtph264: accept non-compliant single FU-A frames

- pkg/conn/conn.go
- pkg/conn/conn_test.go
Updates the connection reading to skip invalid bytes and probes for the interleaved frame/request/response magic bytes.
gortsplib currently dies when trying to play this whereas ffmpeg and VLC are both able to skip over invalid bytes and continue decoding. This change updates the logic so gortsplib mirrors the ffmpeg/VLC behavior.
Context: I am working with this camera https://www.axis.com/products/canon-vb-h47 which seems to throw this error on RTSP play:
```
buffer length exceeds 64
```
I traced it down to some weird packet behavior from the camera, specifically it seems to send:
```
[interleaved frame][random garbage bytes][another interleaved frame]
```
I suspect that the random garbage bytes are some corrupted interleaved frame that's missing the header. I do not know why.
Packet …
> Skip invalid bytes in connection read

- client_media.go
- client_play_test.go
- client_record_test.go
- client_udp_listener.go
- server_play_test.go
- server_record_test.go
Fixes #612
When the TCP transport protocol is in use, BytesSent and BytesReceived were increased twice.
> client: fix BytesSent / BytesReceived computation (#612)

- async_processor.go
- client.go
- client_format.go
- client_media.go
- client_reader.go
- client_record_test.go
- server_conn.go
- server_conn_reader.go
- server_multicast_writer.go
- server_play_test.go
- server_session.go
- server_session_media.go
> close connections in case of write errors (#613)

- client.go
- client_format.go
- client_media.go
- server_multicast_writer.go
- server_session.go
- server_session_media.go
- server_stream_format.go
- server_stream_media.go
> use a single TCP outgoing buffer each client / session

- async_processor.go
- async_processor_test.go
- client.go
- client_play_test.go
- server_session.go
In https://github.com/bluenviron/gortsplib/pull/655 the change was made in `client.go` to set `writer` to `nil`, before completing the 'closing' of the client. This makes that if someone calls `WritePacketRTPWithNTP` after `writer = nil` but before `c.done` is closed, there is a panic. As described in https://github.com/bluenviron/gortsplib/issues/678. 
I don't fully understand why `c.writer = nil` is needed in the first place. It seems that before https://github.com/bluenviron/gortsplib/pull/655 `c.writer` is never set to `nil`. And after testing the situation of the panic, this resolved it. If someone has a better solution I'm very eager to learn!
> Fix writer nullpointer panic on network reconnect

- server_session.go
> server: fix panic during PAUSE due to race condition (#689)

- examples/server-h264-to-disk/mpegts_muxer.go
This PR fixes an incorrect function call in the example code located in examples/server-h264-to-disk/mpegts_muxer.go.
The issue was caused by the writeH264 function incorrectly calling WriteH265 instead of the correct WriteH264. This caused the example to behave incorrectly when handling H.264 data.
> Fix incorrect function call

- server_conn.go
- server_test.go
Since commit 8c6495c33b3194f1bf34f3f8a87f51907e567915, the server can no longer directly specify the response body to DESCRIBE requests. This is a breaking change and is a limitation for users who manually handle their SDPs. This commit allows setting the body explicitly and takes it into account if the `ServerStream` part of the `OnDecsribe` return value is nil. If neither the stream, nor the body are set, the application panics.
@aler9 if you approve this change, I can amend the tests.
> Allow setting response body in OnDescribe

- pkg/multicast/multi_conn.go
- pkg/multicast/multi_conn_lin.go
- pkg/multicast/single_conn.go
- pkg/multicast/single_conn_lin.go
they are already exposed through multicast.Conn.
> unexport multicast.MultiConn, multicast.SingleConn

- client_media.go
- pkg/rtcpreceiver/rtcpreceiver.go
- pkg/rtcpreceiver/rtcpreceiver_test.go
- pkg/rtcpsender/rtcpsender.go
- pkg/rtcpsender/rtcpsender_test.go
- server_session_media.go
(bluenviron/mediamtx#4476)
also prevents RTCP sender and RTCP reports from being emitted when track has clock rate set to zero.
> fix crash when reading tracks with zero clock rate

- client.go
- client_format.go
- client_media.go
- client_play_test.go
- client_record_test.go
- pkg/rtcpreceiver/rtcpreceiver.go
- pkg/rtcpsender/rtcpsender.go
- server_play_test.go
- server_record_test.go
- server_session.go
- server_session_format.go
- server_session_media.go
- server_stream.go
- server_stream_format.go
- server_stream_media.go
- server_test.go
In client and server, each format now has a fixed, unique, known in
advance SSRC, that is applied to outgoing packets belonging to each
format.
This is needed to support SRTP/MIKEY, that require each format to have
a fixed, unique, and known in advance SSRC.
A secondary effect is that SETUP responses now always contain SSRCs of
each format, regardless of the fact that the first packet has been
produced or not (previously we needed at least one packet, from which
the SSRC was extracted).
> set SSRC of outgoing packets

- server.go
When mediamtx failed to start, It was not clear what port caused the error. Also, there are error messages with the same wording in multiple places, which makes debugging harder.
This PR adds dumping of actual port values in `server.go`.
> server: improve log messages (NFC)

- client.go
- client_media.go
- client_udp_listener.go
- pkg/multicast/multicast.go
Fixes #762
this fixes most errors "found no interface that is multicast-capable and can communicate with IP".
> client: use server interface as multicast interface (#762)

- client_play_test.go
- client_record_test.go
- pkg/ntp/ntp.go
- pkg/ntp/ntp_test.go
- pkg/rtcpreceiver/rtcpreceiver.go
- pkg/rtcpsender/rtcpsender.go
- server_conn.go
- server_play_test.go
- server_record_test.go
- server_session.go
Fixes #869 
Fractional part now is in 1/(2^32) units, while it was in 1/(1^9) units.
> fix encoding and decoding of NTP fractional part (#869)

- pkg/format/format.go
- pkg/format/format_test.go
- pkg/format/klv.go
- pkg/headers/range_test.go
Fixes https://github.com/bluenviron/mediamtx/issues/4848
The encoding name used to identify and mark KLV packets appropriately was typo'd in a few places as "smtpe" ("tpe" vs "pte"). This was causing downstream consumers (including ffmpeg and gstreamer) to not properly identify KLV data streams, and may have caused issues with mediamtx itself identifying KLV data streams (unconfirmed). This typo was introduced in https://github.com/bluenviron/gortsplib/pull/808
This PR fixes the typo and adjusts casing to stay consistent with other encoding-name mappings in this library.
We tested this fix locally by serving an MPEGTS file with KLV data via an RTSP stream directly in mediamtx and receiving the stream in gstreamer:
```
gst-launch-1.0 rtspsrc location="rtsp://127.0.0.1:8554/stream" ! …
```
> Fix typo when identifying KLV packets as SMPTE336M-encoded
